FROM alpine:edge
LABEL maintainer="jonas.toth@student.tu-freiberg.de"

RUN apk update \
 && apk add bash \
            build-base \
            ninja \
            cmake \
            gcc g++ \
            wget \
            unzip \
            rsync
